### ISSUE TITLE
Other missing infos for contributors

### ISSUE THREAD

**Issue by nzambello** [nzambello/ellipsed#11]
As reported by @JohnAkerman in PR #8:
Something that would be useful to add is a section on Versioning; whether we are using SemVar etc. and a list of prerequisites if there are any (npm/yarn versions, ...).

**Comment by JohnAkerman** [comment]
It would be useful to document the coding style such as tab space 2, indenting, comments etc.

**Comment by nzambello** [comment]
Working on it. I'll push changes after merging PR #16 .

**Comment by nzambello** [comment]
Merged in commit [4303a63](https://github.com/nzambello/ellipsed/commit/4303a63713627c10611e0b0fbc9c96d6bbb71bfe)
