### ISSUE TITLE
Add option for title attribute that contains the longer text to be added to tag

### ISSUE THREAD

**Issue by JohnAkerman** [nzambello/ellipsed#14]
I think we should add an option which will be a boolean that defaults to false, that when true will take the pre-formatted longer text and add it as a title attribute on the wrapping tag. This will allow the user to hover over the element to get the pre-trucated version in a tooltip.

This would also introduce the idea of options or settings that the user can customise, perhaps the ability to change the "..." to something else instead, perhaps just a single "."?

**Example screenshot**
![image](https://user-images.githubusercontent.com/2814624/30763974-d6e0b3bc-9fe0-11e7-98a6-a4ac2233efa2.png)

**Comment by nzambello** [comment]
I like the idea of the custom string (substituting the default '...'), why not.
I'll study the title tag with the complete text for accessibility.

**Comment by nzambello** [comment]
@JohnAkerman the title attribute seems not to be a good thing for accessibility, so it could be better to ignore that.

https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/
http://www.mediacurrent.com/blog/dont-rely-title-attribute-accessibility-seo

**Comment by nzambello** [comment]
Verified with an accessibility expert. Using the dots ('...') or a meaningful replacement string is obviously understandable that the text would continue, so it's ok.
