### ISSUE TITLE
Add prettier as pre-commit hook.

### ISSUE THREAD

**Issue by pnicolli** [nzambello/ellipsed#17]
I like it when the code looks the same across the whole library, even if this is a tiny one. How about adding [prettier](https://github.com/prettier/prettier) as a default pre-commit hook?

This is easily achievable as described [in the prettier docs](https://github.com/prettier/prettier#pre-commit-hook).

**Comment by nzambello** [comment]
It's always a good thing. Go! 👍

**Comment by jaydp17** [comment]
Hey!! @pnicolli, @nzambello this seems like something I can do.
Let's first decide on the style we'd want to use.

I usually prefer,
- single quotes
- trailing comma everywhere except functions params
- line width of 120

Let me know what you guys think about it

**Comment by pnicolli** [comment]
I had no time to do this yet and I won't have time to work on this in the next days, so feel free to open a PR for this, @jaydp17 

About the style, I usually go with similar options:

- single quotes
- trailing comma either like you suggested or everywhere
- default line width

Anyway, I'm ok with extending line width to 120 and setting trailing comma like you suggested, what do you think @nzambello ?

**Comment by nzambello** [comment]
Thanks @jaydp17 for getting involved.
I agree with your suggested options, submit a PR when you have done.

Welcome to the project! If you want to communicate or ask anything, you can join the gitter channel.
