### ISSUE TITLE
replaceStr example in demo

### ISSUE THREAD

**Issue by nzambello** [nzambello/ellipsed#18]
As @JohnAkerman made in PR #16, we should add an example of `replaceStr` usage in the demo

**Comment by JohnAkerman** [comment]
I’m going to plan a more interactive demo page that people can use to see the options. I’ll keep you updated so you can tell me your thoughts.

**Comment by nzambello** [comment]
I'm doing this. What were you thinking about?

I'm trying to add an <input> for `replaceStr` and perhaps another <input> for the number of rows: I said perhaps because using buttons is simplier and more effective.

**Comment by nzambello** [comment]
I'm working on it in my branch `nicola_replacestr`.
https://github.com/nzambello/ellipsed/tree/nicola_replacestr

**Comment by JohnAkerman** [comment]
I was thinking perhaps a textarea that is prepopulated that can be typed into for the example text.  For the ‘replaceStr’ we could have an input that allows the value to be typed in. The number of rows to show could be an input or even a slider. 

Would be nice to make it interactive and nice to use. Maybe with some preset options to show different examples.

**Comment by nzambello** [comment]
Ok, I'll think about your ideas. Meanwhile, I'm merging the basic enhancement with what I have done.
EDIT: see [f7e956f](https://github.com/nzambello/ellipsed/commit/f7e956fc9c50d24583ad82083f3574ae12b1688e)

I think there are many ways to make the demo page more complete and interesting. If you have precise ideas, go and try! 👍 

I think the slider is cool, but buttons are immediately understandable. I don't know.
It's not an urgent task.
