### ISSUE TITLE
Responsive checkbox in demo not working after first call

### ISSUE THREAD

**Issue by pnicolli** [nzambello/ellipsed#27]
The responsive checkbox in the demo is correctly read when you first click uno of the five ellipsis buttons. After you use an ellipsis with the responsive option active, though, you can't switch it off. Well, the checkbox does switch off, but the window resize event handler is already there and won't go away.

I haven't found a quick way to remove it from the demo, I am submitting a PR in the next few minutes with a workaround in order to make it work, which is reloading the page when you switch off the checkbox.

In order to remove a listener from the window object, you need to have a reference to the function that was called, and only the lib code has it, so my guess is that we have to export another function from the lib, that resets the responsive option by removing the listener.

**Comment by nzambello** [comment]
I saw it few days ago, and the only way is to reload the page as you said.
It's an issue only for the demo, because on a real use case, I found no reason to re-call `ellipsis` more than one time.

**Comment by pnicolli** [comment]
Yes, I agree with that, still I think it would be good, without any hurry, to give some way to remove the effects of the ellipsis function. I actually have an idea about how to implement that, I will try to write something as soon as I can.

**Comment by nzambello** [comment]
Fixed in #28

**Comment by nzambello** [comment]
Reopening waiting for the more sophisticated version proposed by @pnicolli in #29.
