### ISSUE TITLE
Add documentation for disabling responsiveness

### ISSUE THREAD

**Issue by pnicolli** [nzambello/ellipsed#30]
One of the latest PRs introduced a possible [return value for the `ellipsis` function](https://github.com/nzambello/ellipsed/blob/9482c35ab5c6768e694c8369665981c1e0409059/src/ellipsed.js#L89). It also introduced a function used to disable responsiveness for a previous ellipsis call.

I think these new feature should be added to the README. It's not useful to everybody, you normally don't want to remove the responsive option, but since it's there, some documentation on it would be good.

**Comment by nzambello** [comment]
Fixed in d08d099
