### ISSUE TITLE
Uncaught ReferenceError: ellipsis is not defined

### ISSUE THREAD

**Issue by Murphy1976** [nzambello/ellipsed#38]
I'm attempting to truncate a paragraph with the class "carousel-item-description" to 3 lines, and add some options, but I continuously get the following error:

Uncaught ReferenceError: ellipsis is not defined

ellipsis('.carousel-item-description', 3, {replaceStr: '...', responsive: true, debounceDelay: 100});
How is the above call incorrect?

**Comment by nzambello** [comment]
Hi @Murphy1976, the function call is correct.

How did you imported the library? In [this](https://github.com/nzambello/ellipsed#import) section of the README are shown several methods, which did you used?

**Comment by nzambello** [comment]
Hi @Murphy1976, are you still having issues? May I help you?
Otherwise, I'd like to close this.
