### ISSUE TITLE
Ampersand getting encoded as &amp;

### ISSUE THREAD

**Issue by jonraedeke** [nzambello/ellipsed#41]
Ampersand in content targeted is getting converted to &amp;. Is there an option I am missing that would avoid this? Thanks

**Comment by jonraedeke** [comment]
Sorry, it turns out that my implementation was the issue. I was using this with Drupal behaviors and it was getting re-applied a few times. Thank you for this library.

**Comment by nzambello** [comment]
You're welcome
Thank you for the feedback!
