### ISSUE TITLE
Establish a list of supported browsers

### ISSUE THREAD

**Issue by JohnAkerman** [nzambello/ellipsed#7]
I think it would be beneficial to produce a list of supported browsers.  We could even look into using [SauceLabs ](https://saucelabs.com/)to perform automated tests on any pushes with an indicator on the status per browser.

**Comment by pnicolli** [comment]
I like the idea, this list is one of the next steps that @nzambello recently discussed as a next step.

I just pushed a PR with some more usage infos, and a list of supported browsers could definitely be something related coming soon.

I will look further into SauceLabs asap.

**Comment by nzambello** [comment]
Thank you @JohnAkerman. As @pnicolli said, I already was interested in.
SauceLabs could be very interesting solution.

**Comment by JohnAkerman** [comment]
Here is a list of automated testing tools, as there are alternatives to SauceLabs. Some of these are free too.

- [Travis CI](https://travis-ci.org/)
- [TeamCity](https://www.jetbrains.com/teamcity/)
- [AppVeyor](https://www.appveyor.com/)
- [CodeShip](https://codeship.com/)
- [Shippable](https://www.shippable.com/)
- [Jenkins](https://jenkins.io/)

**Comment by nzambello** [comment]
Tested on last two versions of Chrome, Firefox and Safari. Tested on IE 11 also.

Automatic testing could be an overhead for our purpouse and it needs a lot of work for headless (and I don't know how to test if the function is working with a script on multiple browsers).
@JohnAkerman Suggestions?

**Comment by JohnAkerman** [comment]
Just an update to this, I have tested in the following browsers:

**Working**
- IE10 - Windows 7
- IE9 - Windows 7
- Edge 15 - Windows 10
- Safari 11 - Mac OSX 10.13
- Mobile Safari 8  - iPhone 6

**Not Working**
- IE 8 - Windows XP
- IE 7 - Windows XP

**Comment by nzambello** [comment]
Ok, but I don't want to take care of IE versions older than the 11th, so we are ok with this.
Anyway, thank you for your tests.

**Comment by pnicolli** [comment]
Actually, stating that this lib works on IE9+ is a nice addes bonus, imho, even if you did not care too much about that version, when you started.

About IE7 and 8, I expected that this would not work correctly, but it’s no big deal.

Thanks @JohnAkerman for the update!
